name: sphnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - build
  - pybind11
  - pytest
  - qcelemental
  - qcengine
  - scipy
  - pandas
  - numpy
  - numba
  - wandb
  # PyTorch CPU / Metal
  - pytorch=2.1.0
  - torchvision=0.15.*
  - torchaudio=2.1.0
  - pytorch-lightning
  - tensorboardx
  # SPHNet 及相关工具
  - e3nn
  - hydra-core
  - rdkit
  - transformers
  - conda-forge::submitit
  - pip:
    - pyscf==2.4.0
    - apsw
    - torch_runstats
    - lmdb
    - mlflow
    - azureml-mlflow
    - azure-ai-ml
    - azure-identity
    - wandb
    - syrupy
    - ray
    - orjson
    - ase
    - gdown
    - pyg-lib
    - torch-cluster==1.6.3
    - torch-ema==0.3
    - torch-geometric==2.6.1
    - torch-runstats==0.2.0
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torch-spline-conv==1.2.2
