name: sphnet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - build
  - pybind11
  - pytest
  - qcelemental
  - qcengine
  - scipy
  - pandas
  - numpy
  - numba
  - wandb
  # torch
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision
  - pytorch::torchaudio=2.1.0
  - pytorch::pytorch-cuda=12.1
  - pytorch-lightning
  - tensorboardx
  # SPHNet
  - e3nn
  - hydra-core
  - rdkit
  - transformers
  # ocp
  - conda-forge::submitit
  - pip:
    - pyscf==2.4.0
    - apsw
    - cupy-wheel
    - torch_runstats
    - lmdb
    - mlflow
    - azureml-mlflow
    - azure-ai-ml
    - azure-identity
    # wandb
    - wandb
    # ocp
    - syrupy
    - ray
    - orjson
    # SPHNet
    - ase
    - gdown
    - pyg-lib
    - --find-links https://data.pyg.org/whl/torch-2.1.0+cu121.html
    - torch-cluster==1.6.3+pt21cu121
    - torch-ema==0.3
    - torch-geometric==2.6.1
    - torch-runstats==0.2.0
    - torch-scatter==2.1.2+pt21cu121
    - torch-sparse==0.6.18+pt21cu121
    - torch-spline-conv==1.2.2+pt21cu121
